# Generated by Django 6.0.5 on 2026-05-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/', verbose_name='image'),
        ),
    ]
